name:                reactive-markup
version:             0.1.0.0
github:              "Simre1/reactive-markup"
homepage:            https://github.com/Simre1/reactive-markup#readme
license:             MIT
author:              "Simon"
copyright:           "2020 Simon"


description:         Declarative GUI markup

dependencies:
- base >= 4.7 && < 5
- text > 1.2 && < 1.3
- unordered-containers > 0.2 && < 0.3
- containers > 0.6.2 && < 0.6.3
- colour > 2.3 && < 2.4

library:
  source-dirs: src

tests:
  reactive-markup-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - reactive-markup
    - hspec

default-extensions:
  - OverloadedLabels
  - OverloadedStrings
  - GADTs
  - MultiParamTypeClasses
  - TypeFamilies
  - TypeOperators
  - DataKinds
  - DeriveFunctor
  - FlexibleContexts
  - FlexibleInstances
  - ScopedTypeVariables
  - RankNTypes
  - TypeApplications
  - FunctionalDependencies